name: Build dxapi

on:
  workflow_dispatch:
  push:
    branches: [main, wip-workflow]
  pull_request:
    types: [opened, synchronize]
    branches:  [main, wip-workflow]
    
jobs:
  Build-Dxapi-Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Build Dxapi
        run: make -C ./dxapi/.
        env: 
          CC: clang
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dxapi-linux
          path: |
            ./dxapi/iclude/native/**/*.h
            ./dxapi/bin/libdxapi-x64.a
            
#   Build-Dxapi-MacOS:
#     runs-on: macos-latest
#     steps:
#       - name: Check out repository code
#         uses: actions/checkout@v2
#         with:
#           submodules: 'recursive'
#       - name: Build Dxapi
#         run: make -C ./dxapi/.
#         env:
#           CC: clang
#           OS: MACOS
#       - name: Archive artifacts
#         uses: actions/upload-artifact@v2
#         with:
#           name: dxapi-macos
#           path: |
#             ./dxapi/iclude/native/**/*.h
#             ./dxapi/bin/libdxapi-x64.a
            
#   Build-Dxapi-Windows:
#     runs-on: windows-latest
#     steps:
#     - name: Check out repository code
#       uses: actions/checkout@v2
#       with:
#         submodules: 'recursive'
#     - name: Use MSBuild
#       uses: microsoft/setup-msbuild@v1.0.2
#     - name: Build Solution
#       run: msbuild ./dxapi/dxapi.sln /p:configuration=release /p:platform=x64 /t:rebuild
#     - name: Build Debug Solution
#       run: msbuild ./dxapi/dxapi.sln /p:configuration=debug /p:platform=x64 /t:rebuild
#     - name: Archive artifacts
#       uses: actions/upload-artifact@v2
#       with:
#         name: dxapi-windows
#         path: |
#           ./dxapi/iclude/native/**/*.h
#           ./dxapi/bin/dxapi-x64.lib
#           ./dxapi/bin/dxapi-x64d.lib
#           ./dxapi/bin/dxapi-x64d.pdb

  Build-Dxapi-Python38-Linux:
    runs-on: ubuntu-latest
    needs: [Build-Dxapi-Linux]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Build Dxapi
        run: |
          make -C .
          cp ./dfp/lib/linux/64/libDecimalNative.so ./bin/release/linux/x64/py38/
        env: 
          CC: clang
          PYTHON_VERSION: 38
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dxapi-linux
          path: |
            ./dxapi/iclude/native/**/*.h
            ./dxapi/bin/libdxapi-x64.a
    
